### ISSUE TITLE
What is the special handling for secrets?

### ISSUE THREAD

**Issue by ghost** [pivotal-cf/docs-book-tiledev#17]
It is a bit ambiguous what the special handling is for secrets. Can you provide more complicated password examples? How do we use quotes, single quotes, double quotes? What needs to be escaped. Can you reference a page that explains a bit more about the special handling, or at least a hint to what keywords to search for.

**Comment by ghanna2017** [comment]
@pspinrad Hi, do you know who the SME is for this?

**Comment by pspinrad** [comment]
@ghanna2017 @sadvani This is re: "Note the special handling" here: http://docs.pivotal.io/tiledev/pcf-command.html#deploy-tiles  Example in docs has secret password `SquarePants` but what if you want to set the password default value to something with quotes or other special chars?

**Comment by pspinrad** [comment]
`secret` type property values can include quotes and other special characters-- the "special handling" just means you hafta specify them as a hash, e.g. 
> password: { 'secret': Square'Pants }

Changed docs to clarify: http://docs-pcf-staging.cfapps.io//tiledev/pcf-command.html#deploy-tiles
Thanks for bringing this up @nevenc-pivotal !
