### ISSUE TITLE
`cf push`ed packages do not run in their own VMs

### ISSUE THREAD

**Issue by mboldt** [pivotal-cf/docs-book-tiledev#34]
https://github.com/pivotal-cf/docs-book-tiledev/blob/689f5c39ea5450ce53c86348e0437ebf1563d982/docs-content/tile-structure.html.md.erb#L201

A package type that is `cf push`ed (app, app-broker, docker-app, docker-app-broker) will run its process in a container on a Diego cell, not in its own VM.

docker-bosh and bosh-release packages will run processes in its own BOSH VM.

(For completeness, external-broker and buildpack packages do not start long-running processes.)

**Comment by pspinrad** [comment]
Thanks for the correction, @mboldt !  So, external-broker packages define (one-time) tasks, not long running processes?  How does that work-- like, for external services, the broker task spins up on demand when called via the API?  Seems like that would take a while, but I'm prob missing something...

**Comment by pspinrad** [comment]
@mboldt also, where do external-broker and buildpack packages run-- on Diego cells, as Tasks (not LRPs), right?  I'm putting all this info into a new "Where Package Processes Run" subsection.  Thanks!

**Comment by mboldt** [comment]
external-broker will register a service broker whose process is not managed by PCF. Buildpack registers a custom buildpack with PCF, cf. https://docs.cloudfoundry.org/buildpacks/, https://docs.cloudfoundry.org/adminguide/buildpacks.html.
