### ISSUE TITLE
Support for stack dropdown type?

### ISSUE THREAD

**Issue by kvmw** [pivotal-cf/docs-book-tiledev#50]
### Is your feature request related to a problem? Please describe.

We need to let operator to choose the backing applications `stack`, during the tile installation. 

### Describe the solution you'd like

It would be nice to have a dropdown type, similar to vm_type_dropdown or stemcell_selector to poplulate the available stacks automatically and let the user/operator to choose between the available stacks. 

### Describe alternatives you've considered

Our current workaround is a `string` input, which is prone to errors, typos and ...

Another option would be a dropdown type with hard coded  stack values. The problem with this approach is that we are not aware of available stacks in the customer foundation.

**Comment by bobbygeeze** [comment]
When this enhancement is ready please create a PR and let me know about documentation. Thanks

**Comment by anita-flegg** [comment]
@kvmw -- I think this PR should be in a code repo, not the doc repo. If the code is changed, then we will also need a doc PR to update the documentation. Thanks.

**Comment by kvmw** [comment]
@anita-flegg  Sorry, I don't know why i've created this ticket here :|
