### ISSUE TITLE
"property reference" descriptions incorrectly says "holds a boolean value"

### ISSUE THREAD

**Issue by kkallday** [pivotal-cf/docs-book-tiledev#8]
Hi,

I noticed that this page (https://docs.pivotal.io/tiledev/property-reference.html#property-blueprints) says that many properties hold boolean value. I think some of these might be incorrect. For instance, the description for `uuid` says "Holds a boolean value". I'd expect it to say something like "Holds a uuid (without hyphens) as a string".

**Comment by animatedmax** [comment]
Hi @kkallday We correct the https://docs.pivotal.io/tiledev/property-reference.html#property-blueprints page. Thanks for pointing out the issue!
